### ISSUE TITLE
Please release latest versions on CocoaPods.

### ISSUE THREAD

**Issue by alexandreos** [Olapic/Olapic-SDK-iOS#25]
Please update the podspec file for every release of the project, including minor ones like version 2.0.3, so that people can get it from CocoaPods.
Please take a look at https://guides.cocoapods.org/making/getting-setup-with-trunk.html for  more information.

Thanks,

**Comment by homer0** [comment]
@alexandreos We'll be taking care of this soon. Sorry about the issue.

**Comment by homer0** [comment]
@alexandreos It should be working now; can you check?

**Comment by alexandreos** [comment]
@homer0, Awesome, it looks good now, thank you 👍

**Comment by alexandreos** [comment]
Actually, when I integrate it with CocoaPods: `pod 'Olapic-SDK-iOS', '~> 2.0.3'`, `pod install` creates a Olapic-SDK-iOS folder with only headers, which are not visible to my project files.
Tried to import Olapic SDK with:

`@import Olapic-SDK-iOS;`

or

`#import <OlapicSDK.h>`

with no luck.

Xcode does not find the file.

I have many other pods installed and they are working correctly, so this is not a problem with my CocoaPods setup. Am I missing anything?

Thanks.

**Comment by alexandreos** [comment]
Just to complement, my Podfile is set to use pods as frameworks (`use_frameworks!`)

**Comment by homer0** [comment]
@alexandreos Hi, we'll take a look and let you know; we pushed it like any other library.

**Comment by homer0** [comment]
@alexandreos Hi! Sorry for the delay on this; we found the issue is related to the fact that our SDK is an static library without source (`.a`), so it seems like we have to do a few extra tweaks in order to make it work properly with CocoaPods.

I'll let you know the moment we push the changes!

**Comment by homer0** [comment]
@alexandreos Hi, again, sorry for the delay. There were a few things involved on this issue:

1. `use_frameworks!` tends to mess up the search paths (there's a lot of chat on stackoverflow and the Cocoapod repo about this... and the solutions are crazy :P).
2. We were exporting our spec as a set of headers instead of a framework.
3. Cocoapod wouldn't allow us to set the `public_header_files` for inside the framework folder.

So, if you want to check #26 , we updated the spec so it will export the framework (fixing points `1` and `2`) and we found out that if inherit the pod search path, everything will work just fine.

To give you an example, we created a small demo project with the following `Podfile`:

```
# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'randomProject4' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for randomProject4
  inherit! :search_paths
  pod 'Olapic-SDK-iOS', '~> 2.0.4'
  
  target 'randomProject4Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'randomProject4UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
``` 

And inside the project, we just do `#import <OlapicSDK/OlapicSDK.h>`, then all the OlapicSDK classes are available.

Let me know if this is working for you!

**Comment by alexandreos** [comment]
I've just confirmed and it's working now! 👍 

Thanks!
